### ISSUE TITLE
XBVR application crash when scanning a directory with leading or trailing whitespace character

### ISSUE THREAD

**Issue by hockeypucks** [cld9x/xbvr#1]
**_issue edit_** this issue was incorrectly believed to be a result of scanning a non-C volume. The actual issue is a result of trying to scan a directory that has either a leading/trailing whitespace character (regardless of drive letter). App crash screenshot still applies.

This issue is really a Windows issue and not exclusive to XBVR. More detail regarding the issue can be found here: https://stackoverflow.com/questions/21072767/cant-delete-a-folder-on-windows-7-with-a-trailing-space

Low-priority issue at best. Likely not even worth investigating but perhaps XBVR could ignore / handle these problem directories graciously.

- XBVR 0.1.5 on a Windows10 64-bit (Enterprise)

![appcrash](https://user-images.githubusercontent.com/50936978/58262134-aa9bd480-7d47-11e9-91fa-ff4b8b193f93.png)

**Comment by cld9x** [comment]
Thanks for the detailed report - gonna have a look at it soonish
