### ISSUE TITLE
"Off-by-2" errors in CzechVR scene data.

### ISSUE THREAD

**Issue by xbvr-account** [cld9x/xbvr#76]
I ran a fresh scene scrape on 0.2.1 and am noticing a discrepancy in the CzechVR data.

## Reproducing

The easiest way to view this issue is by viewing in a SQLite viewer. Example:

![Capture](https://user-images.githubusercontent.com/53242135/61830540-660ce200-ae39-11e9-8397-78748422e192.PNG)

The scene `czech-vr-fetish-191` (highlighted in image) has the correct `title`, but the `filenames_arr,cover_url,scene_url` fields are all mistakenly from  `czech-vr-fetish-193` (two IDs above). 

It looks like it starts with the first two scenes, but doesn't grow after that. `czech-vr-001` has an off by 1 error, then `czech-vr-002` has an off by 2 error, and everything after is off by two:

![Capture2](https://user-images.githubusercontent.com/53242135/61831166-04e60e00-ae3b-11e9-81f8-b3b947ce8285.PNG)

## Speculating solution

I believe the issue is in [this part of the scraper](https://github.com/cld9x/xbvr/blob/master/pkg/scrape/czechvr.go#L48-L54). The selector `div.nazev h2` receives two hits on the page for the scene `czech-vr-002`: `www[.]czechvrnetwork[.]com/detail-699-lenka-6`. So on the second pass, it ends up setting `sc.SiteID` and `sc.Title` incorrectly, based on a hit from the "related videos" section on the page.

**Comment by xbvr-account** [comment]
@cld9x Note, I believe users would have to delete their DB file (or manually delete the effected rows) in order to see the correct data? If I'm not mistaken, the scrape process will avoid pulling a scene it already has data for.

**Comment by cld9x** [comment]
@xbvr-account yes, it wouldn't hurt to start over

btw, I've been pondering about having some troubleshooting section in app, and this makes perfect case for it
